name: mobile_app_flutter
description: Mobile application for Digital Agriculture
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  fl_chart: ^0.66.0
  image_picker: ^1.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
